FROM node:14.17.5-stretch

WORKDIR /SiteForTestingUsersFront

COPY ./testingusers_frontend/ /SiteForTestingUsersFront/testingusers_frontend/

COPY ./testingusers_frontend/src /SiteForTestingUsersFront/testingusers_frontend/

WORKDIR /SiteForTestingUsersFront/testingusers_frontend

RUN npm install -g npm

COPY ./testingusers_frontend/package.json /SiteForTestingUsersFront/testingusers_frontend/
COPY ./testingusers_frontend/package-lock.json /SiteForTestingUsersFront/testingusers_frontend/

RUN npm install
RUN npm run build
