# Generated by Django 4.0.5 on 2022-10-25 16:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_avatar',
            field=models.ImageField(default='default_user_avatar.png', upload_to=users.models.user_upload_to_path_avatar, verbose_name='UserAvatar'),
        ),
    ]
