# Generated by Django 4.0.5 on 2022-09-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answer_options_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
    ]
