# Generated by Django 4.0.5 on 2022-11-13 08:23

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=post.models.set_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='post.category'),
        ),
    ]
