# Generated by Django 4.0.5 on 2022-11-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exams',
            new_name='exam',
        ),
    ]
