# Generated by Django 4.0.5 on 2022-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examquestion_examanswer_alter_exam_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to='exam.examquestion'),
        ),
    ]
