# Generated by Django 4.0.5 on 2022-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='No name test', max_length=100),
        ),
    ]
