# Generated by Django 4.0.5 on 2022-11-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to='exam.examquestion'),
        ),
    ]
